FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY Trainer/*.csproj ./Trainer/
RUN dotnet restore

# copy everything else and build app
COPY Trainer/. ./Trainer/
WORKDIR /app/Trainer
RUN dotnet publish -c Release -o out


FROM microsoft/dotnet:2.1-aspnetcore-runtime AS runtime
WORKDIR /app
COPY --from=build /app/Trainer/out ./
ENTRYPOINT ["dotnet", "Trainre.dll"]