export class foodItem {
    id: number;
    name: string;
    amount: number;
    calories: number = 0;
    energy: number = 0;
    alcohol: number = 0;
    caffiene: number = 0;
    water: number = 0;
    carbs: number = 0;
    fiber: number = 0;
    starch: number = 0;
    sugars: number = 0;
    netCarbs: number = 0;
    fat: number = 0;
    monounsaturated: number = 0;
    polyunsaturated: number = 0;
    omega3: number = 0;
    omega6: number = 0;
    saturated: number = 0;
    transFats: number = 0;
    cholesterol: number = 0;
    protein: number = 0;
    cystine: number = 0;
    histidine: number = 0;
    isoleucine: number = 0;
    leucine: number = 0;
    lysine: number = 0;
    methionine: number = 0;
    phenylalanine: number = 0;
    threonine: number = 0;
    tryptophan: number = 0;
    tyrosine: number = 0;
    valine: number = 0;
    b1: number = 0;
    b2: number = 0;
    b3: number = 0;
    b5: number = 0;
    b6: number = 0;
    b12: number = 0;
    folate: number = 0;
    vitaminA: number = 0;
    vitaminC: number = 0;
    vitaminD: number = 0;
    vitaminE: number = 0;
    vitaminK: number = 0;
    calcuim: number = 0;
    copper: number = 0;
    iron: number = 0;
    magnesium: number = 0;
    manganese: number = 0;
    phosphorus: number = 0;
    potassium: number = 0;
    selenium: number = 0;
    sodium: number = 0;
    zinc: number = 0;
    createdAt: Date;
    createdBy: string;
    updatedAt: Date;
    updatedBy: string;
}