version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: trainer_web
    # deploy:
    #   replicas: 3
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure
    ports:
      - "4400:80"
    # depends_on:
    #   - db
    networks:
      - webnet  
  # db:
  #   image: "microsoft/mssql-server-linux"
  #   ports: 
  #     - "1433:1433"
  #   environment:
  #       SA_PASSWORD: "1234"
  #       ACCEPT_EULA: "Y"
networks:
  webnet: