FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY Trainer/*.csproj ./Trainer/
COPY Articles.Core/*.csproj ./Articles.Core/
COPY AttachmentsManager/*.csproj ./AttachmentsManager/
COPY Authentication/*.csproj ./Authentication/
COPY Lookups.Core/*.csproj ./Lookups.Core/
COPY MailProvider.Core/*.csproj ./MailProvider.Core/
COPY Products.Categories.Core/*.csproj ./Products.Categories.Core/
COPY Products.SubCategories.Core/*.csproj ./Products.SubCategories.Core/
COPY Shared.Core/*.csproj ./Shared.Core/
COPY test.core/*.csproj ./test.core/
COPY Trainer.EF/*.csproj ./Trainer.EF/
RUN dotnet restore

# copy everything else and build app
COPY Trainer/. ./Trainer/
COPY Articles.Core/. ./Articles.Core/
COPY AttachmentsManager/. ./AttachmentsManager/
COPY Authentication/. ./Authentication/
COPY Lookups.Core/. ./Lookups.Core/
COPY MailProvider.Core/. ./MailProvider.Core/
COPY Products.Categories.Core/. ./Products.Categories.Core/
COPY Products.SubCategories.Core/. ./Products.SubCategories.Core/
COPY Shared.Core/. ./Shared.Core/
COPY test.core/. ./test.core/
COPY Trainer.EF/. ./Trainer.EF/

WORKDIR /app/Trainer
RUN dotnet publish -c Release -o out


FROM microsoft/dotnet:2.1-aspnetcore-runtime AS runtime
WORKDIR /app
COPY --from=build /app/Trainer/out ./
ENTRYPOINT ["dotnet", "Trainre.dll"]